CarApppTest/Models/Car.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarApppTest.Models
{
    public class Car
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Car Name")]
        public string Name { get; set; }
        [Required]
        public int year { get; set; }
        [ForeignKey("category")]
        public int CategoryId { get; set; } 
        public Category? category { get; set; }
    }
}

CarApppTest/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace CarApppTest.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public ICollection<Car> cars { get; set; }
    }
}

CarApppTest/Models/ErrorViewModel.cs
namespace CarApppTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarApppTest/Controllers/CarsController.cs
using CarApppTest.Data;
using CarApppTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarApppTest.Controllers
{
    public class CarsController : Controller
    {
        private readonly AppDBContext _dbContext;
        public CarsController(AppDBContext db)
        {
            _dbContext = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Car> carList = _dbContext.cars.ToList();
            return View(carList);
        }
        //Get 
        public ActionResult Add()
        {
            selectCategory();
            return View();
        }
        //Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Car car)
        {
            if(ModelState.IsValid)
            {
                _dbContext.cars.Add(car);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }
        public void selectCategory(int selectedId=0)
        {
            List<Category> categories = new List<Category>
            {
                new Category { Id=0 , Name="BMW"},
                new Category { Id=1 , Name="NISSAN"},
                new Category { Id=2 , Name="TOYTA"},
                new Category { Id=3 , Name="BMW"}
            };
            SelectList listItems = new SelectList(categories, "Id", "Name", selectedId);
            ViewBag.CategoryList = listItems;
        }
        //Get 
        public ActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var car = _dbContext.cars.Find(id);
            if(car == null)
            {
                return NotFound();
            }
            selectCategory();
            return View(car);
        }
        //Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                _dbContext.cars.Update(car);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(car);
            }
        }
        //Get 
        public ActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var car = _dbContext.cars.Find(id);
            if (car == null)
            {
                return NotFound();
            }
            selectCategory();
            return View(car);
        }
        //Post 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Car car)
        {
         
                _dbContext.cars.Remove(car);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
        }
    }
}

CarApppTest/Controllers/HomeController.cs
using CarApppTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarApppTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarApppTest/Views/Cars/Add.cshtml
@model Car
@{
    ViewData["Title"] = "Add";
}

<h3>Add New Car</h3>
<hr/>
<div asp-validation-summary="All"></div>
<form method="post"> 
    <fieldset>
        <legend>Add New Car </legend>
        <div class="form-group">
            <label asp-for="Name" class="form-label mt-4"></label>
            <input type="text"  asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-bg-danger"></span>
        </div>
        <div class="form-group">
            <label  asp-for="year" class="form-label mt-4"></label>
            <input type="text"  asp-for="year" class="form-control" >
            <span asp-validation-for="year" class="text-bg-danger"></span>
        </div>
        <hr />
        <div>
            <label asp-for="CategoryId"></label>
            <hr/>
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.CategoryList">
            </select>
        </div>
        <hr />
        <div class="align-content-center">
            <button type="submit" class="btn btn-primary" style="width:150px"> Save </button>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <a asp-action="Index" asp-controller="Cars" class="btn btn-secondary" style="width:150px">
                Back
            </a>
        </div>
        </fieldset>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

CarApppTest/Views/Cars/Delete.cshtml
@model Car
@{
    ViewData["Title"] = "Delete";
}

<h3>Delete Car</h3>
<hr />
<div asp-validation-summary="All"></div>
<form method="post">
    <fieldset>
        <legend>Delete Car </legend>
        <div class="form-group">
            <label asp-for="Name" class="form-label mt-4"></label>
            <input type="text" asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-bg-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="year" class="form-label mt-4"></label>
            <input type="text" asp-for="year" class="form-control">
            <span asp-validation-for="year" class="text-bg-danger"></span>
        </div>
        <hr />
        <div>
            <label asp-for="CategoryId"></label>
            <hr />
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.CategoryList">
            </select>
        </div>
        <hr />
        <div class="align-content-center">
            <button type="submit" class="btn btn-danger" style="width:150px"> Delete </button>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <a asp-action="Index" asp-controller="Cars" class="btn btn-secondary" style="width:150px">
                Back
            </a>
        </div>
    </fieldset>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

CarApppTest/Views/Cars/Edit.cshtml
@model Car
@{
    ViewData["Title"] = "Edit";
}

<h3>Edit Car</h3>
<hr />
<div asp-validation-summary="All"></div>
<form method="post">
    <fieldset>
        <legend>Edit Car </legend>
        <div class="form-group">
            <label asp-for="Name" class="form-label mt-4"></label>
            <input type="text" asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-bg-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="year" class="form-label mt-4"></label>
            <input type="text" asp-for="year" class="form-control">
            <span asp-validation-for="year" class="text-bg-danger"></span>
        </div>
        <hr />
        <div>
            <label asp-for="CategoryId"></label>
            <hr />
            <select class="form-control" asp-for="CategoryId" asp-items="@ViewBag.CategoryList">
            </select>
        </div>
        <hr />
        <div class="align-content-center">
            <button type="submit" class="btn btn-primary" style="width:150px"> Save </button>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <a asp-action="Index" asp-controller="Cars" class="btn btn-secondary" style="width:150px">
                Back
            </a>
        </div>
    </fieldset>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}

CarApppTest/Views/Cars/Index.cshtml
@model IEnumerable<Car>
@{
    ViewData["Title"] = "Index";
}

<h1>Cars Data</h1>
<hr/>
<div class="text-end" >
    <a asp-action="Add" asp-controller="Cars" class="btn btn-primary">
        <i class="bi bi-file-plus"></i>
        &nbsp; Add New Car
        </a>
    </div>
    <hr/>
    <hr/>
    @foreach(var car in Model)
    {
    <div class="grid-container">
        <div>
            <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                <div class="card-header">@car.Name</div>
                <div class="card-body">
                    <h4 class="card-title">@car.Name</h4>
                    <p class="card-text"> The car is created in @car.year</p>
                    <a asp-controller="Cars" asp-action="Edit" asp-route-id="@car.Id" class="btn-sm btn-success">
                        <i class="bi bi-pencil"></i>
                    </a>
                    &nbsp; &nbsp; &nbsp;
                    <a asp-controller="Cars" asp-action="Delete" asp-route-id="@car.Id"  class="btn-sm btn-danger">
                        <i class="bi bi-trash3"></i>
                    </a>
                </div>
            </div>
        </div>
        </div>
    
    }
    

CarApppTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CarApppTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarApppTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel=" stylesheet" href="~/css/bootswatchStyle.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarApppTest.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarApppTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cars" asp-action="Index">Cars</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarApppTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>